/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'DQIMsg'
 * message type.
 */

public class DQIMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 20;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 1;

    /** Create a new DQIMsg of size 20. */
    public DQIMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new DQIMsg of the given data_length. */
    public DQIMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DQIMsg with the given data_length
     * and base offset.
     */
    public DQIMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DQIMsg using the given byte array
     * as backing store.
     */
    public DQIMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DQIMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public DQIMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DQIMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public DQIMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DQIMsg embedded in the given message
     * at the given base offset.
     */
    public DQIMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DQIMsg embedded in the given message
     * at the given base offset and length.
     */
    public DQIMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <DQIMsg> \n";
      try {
        s += "  [sensorId=0x"+Long.toHexString(get_sensorId())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [msgId=0x"+Long.toHexString(get_msgId())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [priorityCount=0x"+Long.toHexString(get_priorityCount())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [startId=0x"+Long.toHexString(get_startId())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [endId=0x"+Long.toHexString(get_endId())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [values=";
        for (int i = 0; i < 5; i++) {
          s += "0x"+Long.toHexString(getElement_values(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sensorId
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sensorId' is signed (false).
     */
    public static boolean isSigned_sensorId() {
        return false;
    }

    /**
     * Return whether the field 'sensorId' is an array (false).
     */
    public static boolean isArray_sensorId() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'sensorId'
     */
    public static int offset_sensorId() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sensorId'
     */
    public static int offsetBits_sensorId() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'sensorId'
     */
    public int get_sensorId() {
        return (int)getUIntBEElement(offsetBits_sensorId(), 16);
    }

    /**
     * Set the value of the field 'sensorId'
     */
    public void set_sensorId(int value) {
        setUIntBEElement(offsetBits_sensorId(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'sensorId'
     */
    public static int size_sensorId() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'sensorId'
     */
    public static int sizeBits_sensorId() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: msgId
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'msgId' is signed (false).
     */
    public static boolean isSigned_msgId() {
        return false;
    }

    /**
     * Return whether the field 'msgId' is an array (false).
     */
    public static boolean isArray_msgId() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'msgId'
     */
    public static int offset_msgId() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'msgId'
     */
    public static int offsetBits_msgId() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'msgId'
     */
    public int get_msgId() {
        return (int)getUIntBEElement(offsetBits_msgId(), 16);
    }

    /**
     * Set the value of the field 'msgId'
     */
    public void set_msgId(int value) {
        setUIntBEElement(offsetBits_msgId(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'msgId'
     */
    public static int size_msgId() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'msgId'
     */
    public static int sizeBits_msgId() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: priorityCount
    //   Field type: int, unsigned
    //   Offset (bits): 32
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'priorityCount' is signed (false).
     */
    public static boolean isSigned_priorityCount() {
        return false;
    }

    /**
     * Return whether the field 'priorityCount' is an array (false).
     */
    public static boolean isArray_priorityCount() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'priorityCount'
     */
    public static int offset_priorityCount() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'priorityCount'
     */
    public static int offsetBits_priorityCount() {
        return 32;
    }

    /**
     * Return the value (as a int) of the field 'priorityCount'
     */
    public int get_priorityCount() {
        return (int)getUIntBEElement(offsetBits_priorityCount(), 16);
    }

    /**
     * Set the value of the field 'priorityCount'
     */
    public void set_priorityCount(int value) {
        setUIntBEElement(offsetBits_priorityCount(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'priorityCount'
     */
    public static int size_priorityCount() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'priorityCount'
     */
    public static int sizeBits_priorityCount() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: startId
    //   Field type: int, unsigned
    //   Offset (bits): 48
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'startId' is signed (false).
     */
    public static boolean isSigned_startId() {
        return false;
    }

    /**
     * Return whether the field 'startId' is an array (false).
     */
    public static boolean isArray_startId() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'startId'
     */
    public static int offset_startId() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'startId'
     */
    public static int offsetBits_startId() {
        return 48;
    }

    /**
     * Return the value (as a int) of the field 'startId'
     */
    public int get_startId() {
        return (int)getUIntBEElement(offsetBits_startId(), 16);
    }

    /**
     * Set the value of the field 'startId'
     */
    public void set_startId(int value) {
        setUIntBEElement(offsetBits_startId(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'startId'
     */
    public static int size_startId() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'startId'
     */
    public static int sizeBits_startId() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: endId
    //   Field type: int, unsigned
    //   Offset (bits): 64
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'endId' is signed (false).
     */
    public static boolean isSigned_endId() {
        return false;
    }

    /**
     * Return whether the field 'endId' is an array (false).
     */
    public static boolean isArray_endId() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'endId'
     */
    public static int offset_endId() {
        return (64 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'endId'
     */
    public static int offsetBits_endId() {
        return 64;
    }

    /**
     * Return the value (as a int) of the field 'endId'
     */
    public int get_endId() {
        return (int)getUIntBEElement(offsetBits_endId(), 16);
    }

    /**
     * Set the value of the field 'endId'
     */
    public void set_endId(int value) {
        setUIntBEElement(offsetBits_endId(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'endId'
     */
    public static int size_endId() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'endId'
     */
    public static int sizeBits_endId() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: values
    //   Field type: int[], unsigned
    //   Offset (bits): 80
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'values' is signed (false).
     */
    public static boolean isSigned_values() {
        return false;
    }

    /**
     * Return whether the field 'values' is an array (true).
     */
    public static boolean isArray_values() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'values'
     */
    public static int offset_values(int index1) {
        int offset = 80;
        if (index1 < 0 || index1 >= 5) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'values'
     */
    public static int offsetBits_values(int index1) {
        int offset = 80;
        if (index1 < 0 || index1 >= 5) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'values' as a int[]
     */
    public int[] get_values() {
        int[] tmp = new int[5];
        for (int index0 = 0; index0 < numElements_values(0); index0++) {
            tmp[index0] = getElement_values(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'values' from the given int[]
     */
    public void set_values(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_values(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'values'
     */
    public int getElement_values(int index1) {
        return (int)getUIntBEElement(offsetBits_values(index1), 16);
    }

    /**
     * Set an element of the array 'values'
     */
    public void setElement_values(int index1, int value) {
        setUIntBEElement(offsetBits_values(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'values'
     */
    public static int totalSize_values() {
        return (80 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'values'
     */
    public static int totalSizeBits_values() {
        return 80;
    }

    /**
     * Return the size, in bytes, of each element of the array 'values'
     */
    public static int elementSize_values() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'values'
     */
    public static int elementSizeBits_values() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'values'
     */
    public static int numDimensions_values() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'values'
     */
    public static int numElements_values() {
        return 5;
    }

    /**
     * Return the number of elements in the array 'values'
     * for the given dimension.
     */
    public static int numElements_values(int dimension) {
      int array_dims[] = { 5,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
