/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'FeedbackMsg'
 * message type.
 */

public class FeedbackMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 4;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 1;

    /** Create a new FeedbackMsg of size 4. */
    public FeedbackMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new FeedbackMsg of the given data_length. */
    public FeedbackMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FeedbackMsg with the given data_length
     * and base offset.
     */
    public FeedbackMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FeedbackMsg using the given byte array
     * as backing store.
     */
    public FeedbackMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FeedbackMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public FeedbackMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FeedbackMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public FeedbackMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FeedbackMsg embedded in the given message
     * at the given base offset.
     */
    public FeedbackMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FeedbackMsg embedded in the given message
     * at the given base offset and length.
     */
    public FeedbackMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <FeedbackMsg> \n";
      try {
        s += "  [sensorId=0x"+Long.toHexString(get_sensorId())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [feedback=0x"+Long.toHexString(get_feedback())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sensorId
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sensorId' is signed (false).
     */
    public static boolean isSigned_sensorId() {
        return false;
    }

    /**
     * Return whether the field 'sensorId' is an array (false).
     */
    public static boolean isArray_sensorId() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'sensorId'
     */
    public static int offset_sensorId() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sensorId'
     */
    public static int offsetBits_sensorId() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'sensorId'
     */
    public int get_sensorId() {
        return (int)getUIntBEElement(offsetBits_sensorId(), 16);
    }

    /**
     * Set the value of the field 'sensorId'
     */
    public void set_sensorId(int value) {
        setUIntBEElement(offsetBits_sensorId(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'sensorId'
     */
    public static int size_sensorId() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'sensorId'
     */
    public static int sizeBits_sensorId() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: feedback
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'feedback' is signed (false).
     */
    public static boolean isSigned_feedback() {
        return false;
    }

    /**
     * Return whether the field 'feedback' is an array (false).
     */
    public static boolean isArray_feedback() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'feedback'
     */
    public static int offset_feedback() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'feedback'
     */
    public static int offsetBits_feedback() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'feedback'
     */
    public int get_feedback() {
        return (int)getUIntBEElement(offsetBits_feedback(), 16);
    }

    /**
     * Set the value of the field 'feedback'
     */
    public void set_feedback(int value) {
        setUIntBEElement(offsetBits_feedback(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'feedback'
     */
    public static int size_feedback() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'feedback'
     */
    public static int sizeBits_feedback() {
        return 16;
    }

}
